# Generated by Django 2.2.12 on 2022-08-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='deanname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='deanrec',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='deansign',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='dsacom',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='dsaname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='dsasign',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='hodname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='hodrec',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='hodsign',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='pconsent',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recomend_crit',
            field=models.CharField(blank=True, choices=[('RECOMEND_CRIT', 'Recommendation Criteria'), ('RECOMMENDED', 'Recommended for Approval'), ('NOT RECOMMENDED', 'Not Recommended')], default='RECOMEND_CRIT', max_length=250),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='unit_posted',
            field=models.CharField(blank=True, choices=[('UNIT POSTED', 'Unit Posted'), ('CAFETERIA', 'Cafeteria'), ('LIBRARY', 'Library'), ('SUPERMARKET', 'Supermarket'), ('ICT UNIT', 'ICT Unit'), ('WATER WORKS', 'Water Works'), ('GENERAL AFFAIRS', 'General Affairs(Cleaning)')], default='UNIT POSTED', max_length=150),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='unithead_comm',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='unithead_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='unithead_sign',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='vcapprove',
            field=models.CharField(blank=True, choices=[('VCAPPROVE', 'Vice Chancellor Approval'), ('APPROVED', 'Approved'), ('NOT APPROVED', 'Not Approved')], default='VCAPPROVE', max_length=250),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='wspcomm',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='wspname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='wspsign',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sign',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
